### ISSUE TITLE
Hexadecimal color setting in widget

### ISSUE THREAD

**Issue by Felix-neko** [charettes/django-colorful#24]
Cannot you add the ablilty to set `hex` colors (like `#FFFFFF`) in color-picking widget?

**Comment by charettes** [comment]
This project defaults on the color input of the browser and provide a shim for older browsers as IE.

I can input hex colors on both Chrome and Firefox native inputs but haven't tested the shim. What browser are you using?

**Comment by Felix-neko** [comment]
Chrome under Windows 7.

And what prefix do you use to input hex colors?

**Comment by charettes** [comment]
When click on the [color input here](https://jsfiddle.net/phvapeyc/) in Chrome I'm presented with a color picker where I can either select a color or input a hexadecimal color (e.g  `#FFFFFF`).

Anyway this issue is not related to this project which main purpose is to provide Django fields for storing colors.
